/* eslint-disable react/no-unescaped-entities */
import React, { useState } from "react";
import Head from "next/head";

import DownloadIcon from "../../../assets/svg-tsx/OutflowArrow";
import Button from "../../inputs/Button";
import { tableOfContentTC } from "../../../data/constants";

const TermsCondition = () => {
  const [selectedContent, setSelectedContent] = useState(1);

  const handleContentClick = (id: any) => {
    setSelectedContent(id);
  };

  return (
    <main className="relative">
      <Head>
        <title>CoopHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-new.png" />
      </Head>
      <section className="">
        <div className="bg-dark-purple  w-full bg-primary p-16">
          <Button
            className="text-lg ff-bold !rounded-md mdx2:!rounded-xl"
            paddingY="p-3.5"
            border
            borderColor="border-white"
            fontSize="text-sm"
            bgColor="bg-transparent"
            textColor="text-white"
            paddingX="px-8"
          >
            Back
          </Button>
          <h3 className="ff-regular text-center text-3xl text-white">
            Terms and Conditions
          </h3>
          <p className="m-auto mt-2 max-w-lg  text-center text-white text-base ff-regular">
            Last updated: July, 2025
          </p>
        </div>

        <div className="flex w-full sm:px-16 px-8 sm:py-24 py-12">
          <div className="w-[30%] hidden md:block sticky top-20 max-h-screen overflow-y-auto  overflow-x-hidden scrollbar">
            <h3 className="ff-regular text-xl font-bold ">Table of Content:</h3>
            <div className="">
              {tableOfContentTC.map((item: any) => (
                <a href={item.href} key={item.id}>
                  <div
                    className={`my-4 max-w-[15rem]  ${
                      selectedContent === item.id
                        ? "text-dark-purple border-l-2 border-dark-purple"
                        : ""
                    }`}
                    onClick={() => handleContentClick(item.id)}
                  >
                    <h3 className="ml-5"> {item.title}</h3>
                  </div>
                </a>
              ))}
            </div>
          </div>
          <div className="w-full ml-10">
            <div className="w-full" id="introduction">
              <h3 className="  text-xl font-bold">Introducton</h3>
              <p className="m-auto mt-4 info-text">
                The following Terms and Conditions (the “Terms”) is a contract
                between you (“the user”) and Bridge Escrow Inc. By registering
                and signing up to use this Platform/Website, you agree that you
                have read, understood, and accepted all of the Terms contained
                in this Agreement. You also accept and agree that you are solely
                responsible for understanding and complying with all laws, rules
                and regulations that may be applicable to your use of the
                Services [MA1]The contract is between Bridge solution (app) and
                the users These Terms are legally binding and serve to govern
                your use of this Website. PLEASE READ AND UNDERSTAND THE TERMS
                CAREFULLY BEFORE AGREEING TO BE BOUND BY THEM. All information
                provided by you will be treated securely and strictly in
                accordance with the Nigeria Data Protection Regulation Act 2023
                and any other extant data protection laws and regulations made
                pursuant thereto.
              </p>
            </div>
            <div className="w-full my-10" id="benefits-of-this-platform">
              <h3 className="font-palanquin  text-xl font-bold">
                2. Benefits of this Platform
              </h3>
              <p className="m-auto mt-4 info-text">
                Bridge Escrow Inc (“The Platform”) is a digital platform that
                provides support for online trade between vendors and customers
                by adoption of the Escrow Payment Model to provide security and
                confidence between transacting parties. Through the Escrow
                payment model, buyers get their goods and vendors receive
                payments for the goods supplied. This is achieved by placement
                of hold on payments until the Purchaser and Vendor on the
                Website have fulfilled their due requirements in the
                transaction. This Escrow feature creates an arrangement where a
                Vendor will not receive payment for the applicable transaction
                until the Purchaser has confirmed that it or its authorised
                representative received the Product and is satisfied, or we have
                reasonable cause to believe that the Purchaser has received a
                satisfactory Product from the Vendor. The use of the Platform is
                subject to the limits and conditions set out in this Agreement.
              </p>
            </div>
            <div
              className="w-full my-10"
              id="transaction-dynamics-of-the-platform"
            >
              <h3 className="font-palanquin  text-xl font-bold">
                Transaction Dynamics of the Platform
              </h3>
              <p className="m-auto mt-4 info-text">
                Purchaser: Bridge is authorised by the Purchaser to release
                payment for the Product to the Vendor within two (2) business
                days of receipt of such Product or such shorter period as agreed
                by the Purchaser and the Vendor, whichever is earlier [the
                “Purchaser Inspection Period”].
              </p>
              <br />
              <p className="m-auto mt-4 info-text">OR</p>
              <p className="m-auto mt-4 info-text">
                File the complaint or disputes relating to the Product before
                the expiration of the Inspection Period and in the manner
                required by us. In the event that you do not release such
                payment, or you do not file any complaint or dispute before the
                expiration of the Purchaser Inspection Period, you hereby
                authorise us to release such payment to the Vendor and agree
                that we will not bear any liability for any issue with the
                Product communicated after the Inspection Period.
              </p>
              <p className="m-auto mt-4 info-text">
                Vendor: If you are a Vendor and you offer and/or sell a Product
                that is not (i) fit for use, (ii) merchantable and/or (iii) of
                good quality, you accept that you may lose that sale and not
                receive payment for such Product and you shall not be entitled
                to any compensation and/or indemnity from us for such Product.
              </p>
              <p className="m-auto mt-4 info-text">
                Where the Purchaser returns a Product, you shall be allowed two
                (2) business days to confirm that the Product is in order and
                meets all conditions for return pre-communicated to the
                Purchaser ("Vendor Inspection Period”). The cost of delivery of
                the returned items shall be borne by the Purchaser. At the end
                of the Vendor Inspection Period, Bridge is authorised by the
                Vendor to return payment for the Product to the Purchaser. If
                you raise a complaint as to the state of the Product, Bridge
                shall investigate and make a decision within 3 business days
              </p>
              <p className="m-auto mt-4 info-text">
                You agree that if you file any dispute or complaint with Bridge
                for a Product whose payment is subject to the Escrow feature,
                you:{" "}
              </p>
              <p className="m-auto mt-4 info-text">
                (i) subject to applicable law, authorise us to use our
                discretion to assist with resolving such dispute on this Website
                and to use our discretion to determine whether the payment
                should be released to the Vendor. We shall use all reasonable
                efforts to work to resolving such dispute fairly based on facts
                made available to us and we may suggest the referral of such
                dispute to a judicial or quasi-judicial authority for
                resolution;
              </p>
              <p className="m-auto mt-4 info-text">
                (ii) agree and understand that we shall not be a party in such
                dispute, and we are not your agents or representatives and/are
                not agents or representatives of either the Vendor or Purchaser;
              </p>
              <p className="m-auto mt-4 info-text">
                (iii) agree to provide all information required for resolution
                of such dispute and to work with us and/or the Purchaser or
                Vendor (as applicable) to promptly resolve the dispute;
              </p>
              <p className="m-auto mt-4 info-text">
                (iv) agree that if you are a Purchaser and you are required to
                return a physical Product to a Vendor before we return held
                funds to you, you shall return such Product promptly, in the
                form shared with you and/or within the time period communicated
                by us or the competent authority.
              </p>
            </div>
            <a
              className="flex space-x-5  my-8 items-center cursor-pointer"
              type="button"
              rel="noopener noreferrer"
              target="_blank"
              href="https://coophub.alat.ng/api/FilesFolder\\638337418223588082.doc"
            >
              <DownloadIcon />
              <h2 className="text-base cursor-pointer font-bold text-dark-purple">
                Download a copy of our terms and conditions
              </h2>
            </a>
            <div
              className="w-full my-10"
              id="responsibilities-of-the-purchaser"
            >
              <h3 className="font-palanquin  text-xl font-bold">
                Responsibilities of the Purchaser
              </h3>
              <p className="m-auto mt-4 info-text">The purchaser shall:</p>
              <div>
                <p>
                  i. inspect Products delivered to you and ascertain that the
                  Products are free from defects, immediately you receive the
                  Products.
                </p>
                <p>
                  ii. to the extent permitted by applicable law, comply with the
                  Vendor’s Conditions that do not conflict with these Terms.
                </p>
                <p>
                  iii. not knowingly deceive any Vendor in the process of
                  communicating your intentions to purchase a Product.
                </p>
                <p>
                  iv. make and/or release payment for Purchased Products in
                  accordance with these Terms and/or as communicated to the
                  Purchaser or by us.
                </p>
              </div>
            </div>
            <div className="w-full my-10" id="responsibilities-of-the-vendor">
              <h3 className="font-palanquin text-xl font-bold">
                Responsibilities of the Vendor
              </h3>
              <p className="m-auto mt-4 info-text">The Vendor shall:</p>
              <div>
                <p>
                  i. ensure that the goods supplied shall be fit for the purpose
                  for which they are commonly used or for any particular purpose
                  specified by the purchaser. The seller guarantees that the
                  goods will perform their intended functions efficiently and
                  effectively.
                </p>
                <p>
                  ii. ensure that the goods shall be of merchantable quality and
                  that they shall be reasonably durable, free from defects, and
                  suitable for their ordinary and customary use. The goods would
                  also conform to the standards generally acceptable within the
                  trade.
                </p>
                <p>
                  iii. ensure that the goods supplied must comply with all
                  relevant laws, regulations, and standards applicable in
                  Nigeria. This includes but is not limited to health, safety,
                  environmental, and labelling requirements.
                </p>
                <p>
                  iv. ensure that the goods supplied are free from defects in
                  materials, workmanship, and design for a specified period. If
                  any defects arise within the inspection period, the vendor
                  shall be responsible for replacement or refund as per the
                  terms and conditions outlined in the agreement.
                </p>
                <p>
                  v. provide all the information necessary when listing Products
                  on this Website and such information should include but is not
                  limited to, a detailed title and sub-title, price, quantity,
                  picture, and description.
                </p>
                <p>
                  vi. expressly state on your Products listing and/or
                  description, all packaging charges, delivery charges, handling
                  charges, administrative charges, insurance costs, other
                  ancillary costs, and charges where applicable.
                </p>
                <p>
                  vii. adhere to the range of Products and prices as provided
                  and as described on your listing on this Website.
                </p>
                <p>
                  viii. keep an up-to-date inventory of all Products listed on
                  this Website and keep your listed Products available.
                </p>
                <p>
                  ix. not list any Product that infringes any third-party
                  intellectual property rights (including copyright, trademark,
                  patent, and trade secrets) or other proprietary rights
                  (including rights of publicity or privacy) or any Product that
                  is counterfeited, illegal, stolen, or fraudulent.
                </p>
                <p>
                  x. contact Purchasers no more than is necessary for processing
                  orders for your Products. In particular and subject to
                  applicable law, you shall not send any advertising email or
                  other commercial advertisements to Users without our prior
                  written agreement or the expressed wish of the Purchaser.
                </p>
                <p>
                  xi. not deceive any User by misrepresenting your Products.
                </p>
                <p>
                  xii. process orders and arrange delivery with all reasonable
                  care. The delivery options and timeline indicated on your
                  listing on this Website are binding, and orders should be
                  fulfilled in accordance with the stated timelines.
                </p>
                <p>
                  xiii. where you cannot fulfil an order, promptly communicate
                  same to the Purchaser.
                </p>
                <p>
                  xiv. attend to any User complaints in relation to the Products
                  in accordance with the period as may be agreed between you
                  and/or such other timelines communicated by us.
                </p>
                <p>
                  xv. ensure that at all times, the phone number(s) and e-mail
                  address(es) for your customer service contact is displayed on
                  your website and the Bridge platform.
                </p>
                <p>
                  xvi. provide to the Purchaser all Vendor’s Conditions which do
                  not conflict with these Terms, and use all reasonable efforts
                  to inform the Purchaser of regulatory guidelines governing the
                  purchase and/or use of the Products where applicable.
                </p>
                <p>
                  xvii. to the extent permitted by applicable law, comply with
                  all Additional Terms and our directives on refunds or
                  chargebacks where applicable.
                </p>
                <p>
                  xviii. where applicable and without prejudice to these Terms
                  (particularly the terms on the Escrow feature), Vendors’
                  return policy in the Vendor’s Conditions must contain clear
                  conditions relevant to the return of Products which shall
                  include but are not limited to criteria under which a return
                  will be accepted, clearly stated time period in which the
                  Purchaser must notify the seller about a return and whether it
                  is the Vendor or Purchaser that will pay delivery fees for
                  Products to be returned.
                </p>
                <p>
                  xix. do such other legal things as may be necessary or
                  incidental to the fulfilment of orders for your Products.
                </p>
              </div>
            </div>
            <div className="w-full my-10" id="logistics-and-delivery">
              <h3 className="font-palanquin  text-xl font-bold">
                Logistics and Delivery
              </h3>
              <p className="m-auto mt-4 info-text">
                You are solely responsible for maintaining the security of your
                Device and for any unauthorised use of your Device to access the
                service. You agree to lock your Device with a password or number
                code whenever it is not in use to prevent unauthorised use of
                the service. In addition, you agree to notify us immediately in
                the event you become aware of any unauthorised use of the
                Service or threat of unauthorised use of the service.
              </p>
              <p className="m-auto mt-4 info-text">
                You understand and agree that in the event of any insurance
                claim for loss, theft and/or damage of Products that you
                requested for delivery using any of the integrated delivery
                options, you shall provide us and/or the insurance company with
                all information required for processing such insurance claims
                including but not limited to purchase receipts of the applicable
                Products.
              </p>
              <p className="m-auto mt-4 info-text">
                You understand and agree that you have the obligation to make
                informed decisions and conduct your due diligence before using
                any of the delivery options on this Website and choosing any of
                the insurance coverage options that may be provided by any
                delivery/logistics/shipping companies on this Website.
              </p>
            </div>
            <div className="w-full my-10" id="security-procedures">
              <h3 className="font-palanquin  text-xl font-bold">
                Security Procedures
              </h3>
              <p className="m-auto mt-4 info-text">
                You are solely responsible for maintaining the security of your
                Device and for any unauthorised use of your Device to access the
                service. You agree to lock your Device with a password or number
                code whenever it is not in use to prevent unauthorised use of
                the service. In addition, you agree to notify us immediately in
                the event you become aware of any unauthorised use of the
                Service or threat of unauthorised use of the service.
              </p>
            </div>
            <div className="w-full my-10" id="availability-and-reversals">
              <h3 className="font-palanquin  text-xl font-bold">
                Security Procedures
              </h3>
              <p className="m-auto mt-4 info-text">
                It is your responsibility to ensure that all transaction
                information is correctly entered and communicated including
                transaction amounts. There may be events during which our
                services will be unavailable. This may be due to factors such as
                scheduled maintenance or interruption in Internet service.
              </p>
            </div>
            <div className="w-full my-10" id="restrictions-on-use">
              <h3 className="font-palanquin  text-xl font-bold">
                Restrictions on Use
              </h3>
              <p className="m-auto mt-4 info-text">
                You agree not to use the Service for any illegal, fraudulent,
                unauthorized, or improper manner or purpose and agree that the
                Service will only be used in a manner that complies with all
                applicable laws, rules and regulations.
              </p>
            </div>
            <div
              className="w-full my-10"
              id="money-laundering-and-terrorism-prohibition"
            >
              <h3 className="font-palanquin  text-xl font-bold">
                Money Laundering and Terrorism Prohibition
              </h3>
              <p className="m-auto mt-4 info-text">
                You hereby agree to comply with the anti-money laundering and
                anti-terrorism regulations; and anti-corruption laws including
                but not limited to the Central Bank of Nigeria (Anti-Money
                Laundering and Combating the Financing of Terrorism in Banks and
                other Financial Institutions in Nigeria) Regulations 2022,
                Economic and Financial Crimes Commission (Establishment, etc.)
                Act 2004; Corrupt Practices and Other Related Offences Cap C31
                Laws of the Federation of Nigeria 2004; Money Laundering
                (Prohibition) Act, 2011 and Terrorism (Prevention) Act 2011.
              </p>
            </div>
            <div className="w-full my-10" id="indemnification">
              <h3 className="font-palanquin  text-xl font-bold">
                Indemnification
              </h3>
              <p className="m-auto mt-4 info-text">
                You hereby agree to indemnify, defend and hold us, our
                employees, agents and affiliates harmless from and against any
                claim, expense, liability, cost, loss or damage (including cost
                of dispute resolution) caused directly or indirectly by your
                failure to comply with the terms of the agreement, your breach
                of representation or warranty, your failure to maintain the
                security of your mobile device and your negligent or intentional
                acts or omission in utilising the service and your violation of
                any applicable law, statute, or regulation relating to your use
                of the service.
              </p>
            </div>
            <div className="w-full my-10" id="limitation-of-liability">
              <h3 className="font-palanquin  text-xl font-bold">
                Limitation of Liability
              </h3>
              <p className="m-auto mt-4 info-text">
                You agree that to the extent not prohibited by applicable law,
                We will not be liable for any direct, indirect, incidental,
                special, consequential or exemplary damages, including, but not
                limited to damages for loss of profits, goodwill, or other
                losses resulting from the use or the inability to use the
                services incurred by you or any third party arising from or
                related to the use of, inability to use , or the termination of
                the use of the Product, regardless of the form of action or
                claim (whether contract, tort, strict liability or otherwise),
                even if we have been informed of the possibility thereof. We
                shall also not be liable for any loss or damage of products by
                any logistics/delivery company accessed via this website and/or
                used by a vendor. We shall not bear any liability for any of the
                insurance coverage options that a user chooses or accesses on
                this website.
              </p>
            </div>
            <div className="w-full my-10" id="disclaimer-of-warranties">
              <h3 className="font-palanquin text-xl font-bold">
                Disclaimer of Warranties
              </h3>
              <br />
              <div className="info-text space-y-4">
                <p>
                  i. You agree that your use of the service is at your own risk
                  and is provided on an "as is" and "as available" basis. Except
                  for warranties which may not be excluded by law, we disclaim
                  all warranties of any kind as to the use of the Product,
                  whether express or implied. We make no warranty that the
                  Product (a) will meet your requirements, or (b) will be
                  uninterrupted, secure, or error-free.
                </p>
                <p>
                  ii. We do not warrant or make any representations regarding
                  the availability, accuracy, reliability, or security of the
                  platform, including but not limited to:
                </p>
                <ul className="list-disc list-inside pl-4">
                  <li>
                    <strong>Rundown Times:</strong> We do not guarantee
                    uninterrupted or error-free operation of the platform. You
                    acknowledge that the platform may be subject to occasional
                    limitations, delays, and downtime. We shall not be liable
                    for any damages or losses arising from such rundown times.
                  </li>
                  <li>
                    <strong>Viruses:</strong> We do not warrant that the
                    platform or any content accessible through it will be free
                    from viruses, malware, or other harmful components. You are
                    responsible for implementing suitable measures to protect
                    your systems and data, and we shall not be liable for any
                    damages or losses resulting from viruses or similar harmful
                    components.
                  </li>
                </ul>
                <p>
                  iii. We do not warrant, endorse, guarantee, or assume
                  responsibility for any third-party products, services, or
                  content accessible through or linked from the platform. Any
                  dealings with third parties are solely between you and the
                  third party, and we shall not be responsible for any damages
                  or losses arising from such dealings.
                </p>
              </div>
            </div>

            <div className="w-full my-10" id="acceptance-of-agreement">
              <h3 className="font-palanquin text-xl font-bold">
                Acceptance of Agreement; Amendment
              </h3>
              <br />
              <div className="info-text">
                <p>
                  Your use of the service constitutes your acceptance of this
                  Agreement and other amendments that may be made from time to
                  time. We will notify you of any material change to the
                  Agreement by email, SMS, or by putting up a link on our
                  website. Such amendments shall become effective upon
                  notification or such later date as may be stated in the
                  notice.
                </p>
                <p>
                  If a change is made for security purposes, we may implement
                  the change without prior notice to you. If you do not agree
                  with the change, you may discontinue using the service.
                  However, your continued use of the service will indicate your
                  acceptance of and agreement to any changes to the Service.
                </p>
              </div>
            </div>

            <div className="w-full my-10" id="legal-rights">
              <h3 className="font-palanquin text-xl font-bold">
                Legal Rights for Events of Fraud, Security Breach or Related
                Conduct
              </h3>
              <br />
              <div className="info-text space-y-4">
                <p>
                  In the event of your participation or suspicion thereof in
                  activities such as fraud, security breach, misuse of the
                  Product and other prohibited activities specified in this
                  Agreement, we shall be entitled to take all preventive or
                  corrective actions permitted under law. This includes but is
                  not limited to:
                </p>
                <ul className="list-disc list-inside pl-4">
                  <li>Restricting your access to the service</li>
                  <li>
                    Blacklisting or freezing the BVN provided in line with CBN
                    regulations
                  </li>
                  <li>
                    Making formal reports to the EFCC, NPF, or other relevant
                    authorities
                  </li>
                  <li>Commencing legal action in a competent court</li>
                </ul>
                <p>
                  Further to the above, you hereby grant us authority to
                  investigate, report, or take other actions as may be necessary
                  to prevent or resolve the events described above and to
                  recover the affected funds.
                </p>
              </div>
            </div>
            <div className="w-full my-10" id="governing-law-dispute-resolution">
              <h3 className="font-palanquin text-xl font-bold">
                Governing Law and Dispute Resolution
              </h3>
              <br />
              <div className="info-text space-y-4">
                <p>
                  i. This Agreement, and your rights and our obligations under
                  this Agreement, are governed by and interpreted in accordance
                  with the laws of the Federal Republic of Nigeria.
                </p>
                <p>
                  ii. Any dispute arising from the use of the service shall
                  first be resolved through mediation between the parties.
                  During this period, the transaction will be placed in a state
                  of <strong>“In Dispute”</strong> until both parties reach a
                  resolution and either:
                </p>
                <ul className="list-disc list-inside pl-4">
                  <li>Mark the transaction as completed, or</li>
                  <li>
                    Mutually agree to cancel the transaction, in which case the
                    funds shall be returned to the Paying Party.
                  </li>
                </ul>
                <p>
                  While the transaction remains in the{" "}
                  <strong>“In Dispute”</strong> state, the transaction funds
                  shall be securely held in the escrow account.
                </p>
                <p>
                  iii. If the dispute is unresolved after mediation, it may be
                  referred to arbitration. Arbitration shall take place at the
                  Lagos State Multi-door Courthouse, Nigeria, conducted by a
                  sole arbitrator, and coordinated in accordance with the
                  Arbitration and Conciliation Act, Cap A18, Laws of the
                  Federation of Nigeria, 2004 and its applicable Rules.
                </p>
                <p>
                  This arbitration option may be offered at our discretion, only
                  for transactions above a stated threshold. While arbitration
                  is ongoing, the transaction shall remain in the{" "}
                  <strong>“In Dispute”</strong> state, and the details shall be
                  forwarded to the Lagos State Multi-door Courthouse for
                  resolution.
                </p>
                <p>
                  iv. The arbitration fees shall be borne by the transacting
                  parties. Once a decision is reached, the outcome shall be
                  documented as an arbitral award, which shall be binding and
                  enforceable under Nigerian law. The transaction funds shall
                  then be released in accordance with the arbitrator’s decision,
                  after which the transaction will be closed. Throughout this
                  process, the funds will remain securely held in the
                  transactional escrow account.
                </p>
              </div>
            </div>

            <div className="w-full my-10" id="miscellaneous">
              <h3 className="font-palanquin  text-xl font-bold">
                Miscellaneous
              </h3>
              <p className="m-auto mt-4 info-text">
                We may waive enforcement of any provision of this Agreement. Any
                such waiver shall not affect our rights with respect to any
                other transaction or modify the terms of this Agreement. No
                waiver of any breach of this Agreement shall constitute a waiver
                of any prior or subsequent breach of this Agreement. If any
                provision of this Agreement is held to be unenforceable or
                invalid by any court or regulatory authority of competent
                jurisdiction, the validity and enforceability of the remaining
                provisions shall not be affected, and in lieu of such invalid or
                unenforceable provision there shall be added automatically, as
                part of this Agreement, a provision as similar in terms as may
                be valid and enforceable, if possible.
              </p>
            </div>
            <div id="contact-us" className="w-full my-10">
              <h3 className="font-palanquin  text-xl font-bold">Contact Us</h3>
              <p className="m-auto mt-4 info-text">
                If you have any questions about these Terms and Conditions,
                please contact us on:
              </p>
              <br />
              <p className="m-auto mt-4 info-text">
                <span className="font-bold">Email: </span>
                purpleconnect@wemabank.com
              </p>
              <p className="m-auto mt-4 info-text">
                <span className="font-bold"> Call us: </span>
                +234 808 411 1207
              </p>
            </div>
            <div className="flex text-lg  flex-wrap gap-4 leading-normal font-medium font-montserrat max-lg:hidden wide:mr-24">
              <Button
                className="text-lg ff-bold !rounded-md mdx2:!rounded-xl"
                paddingY="p-3.5"
                border
                borderColor="border-success"
                fontSize="text-sm"
                bgColor="bg-transparent"
                textColor="text-success"
                paddingX="px-8"
              >
            Back
              </Button>
              <Button className="min-w-max" type="submit">
                Yes, I agree
              </Button>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};

export default TermsCondition;
