name: Deploy Bridge Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server to pull, build, and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_KEY }}
          script: |
            # Navigate to the project directory
            cd /home/ayodele/main/bridge-web-app || exit 1
            
            # Pull the latest source code from the develop branch
            git pull origin main
            
            # Stop the old container and build/start the new one using the existing .env file
            docker compose build || exit 1
            docker compose up -d
